### ISSUE TITLE
Grilled Meat became free, 0 raw meat required 

### ISSUE THREAD

**Issue by FedisGRA** [Donovan522/donovan-7d2d-modlets#35] opened 2022-05-01 19:39 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dyoung522** [comment] 2023-05-19 03:54
Duplicate of #34

**Closed as completed by dyoung522** 2023-05-19 03:54 UTC
Labels: duplicate
